version: '3'
services:
  db:
    image: postgres:13.2
    restart: always
    ports:
      - "5555:5432"
    expose:
      - 5432
    volumes:
      - ~/docker-db/myquotes:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myquotes
      - POSTGRES_USER=myquotes
      - POSTGRES_PASSWORD=some-password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.watermark.low=90%
      - indices.query.bool.max_clause_count=2048
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker-elastic/myquotes:/usr/share/elasticsearch/data

  web:
    build: .
    command: gunicorn project.wsgi:application --config gunicorn.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
