version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5555:5432"
    expose:
      - 5432
    volumes:
      - ~/docker-db/myquotes:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myquotes
      - POSTGRES_USER=myquotes
      - POSTGRES_PASSWORD=some-password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker-elastic/myquotes:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  web:
    build: .
    command: gunicorn project.wsgi:application --config gunicorn.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
