version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - 5432
  web:
    build: .
    command: gunicorn project.wsgi:application --config gunicorn.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
