# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20161211_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Category'),
        ),
    ]
