# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:15
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20170405_2113'),
    ]

    operations = [
        UnaccentExtension()
    ]
