# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20170408_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='private',
            field=models.BooleanField(default='False'),
        ),
    ]
